//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StartupCentral.DAL.EntityModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class startupcentraldkEntities : DbContext
    {
        public startupcentraldkEntities()
            : base("name=startupcentraldkEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<userMessages> userMessages { get; set; }
        public virtual DbSet<newsLetterSubscriptions> newsLetterSubscriptions { get; set; }
        public virtual DbSet<userForretningsPlan> userForretningsPlan { get; set; }
        public virtual DbSet<userPitch> userPitch { get; set; }
        public virtual DbSet<formularLogger> formularLoggerSet { get; set; }
        public virtual DbSet<activeMembers> activeMembers { get; set; }
        public virtual DbSet<activePlatformMembers> activePlatformMembers { get; set; }
    }
}
