//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StartupCentral.DAL.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class userPitch
    {
        public System.Guid Id { get; set; }
        public string PitchName { get; set; }
        public Nullable<System.Guid> owner { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<bool> Completed { get; set; }
        public Nullable<bool> English { get; set; }
        public string Picture { get; set; }
        public string Agenda { get; set; }
        public string LookFor { get; set; }
        public string MoneyUsage { get; set; }
        public string CompanyDesc { get; set; }
        public string TeamDesc { get; set; }
        public string SatisfyDesc { get; set; }
        public string MarketDesc { get; set; }
        public string Traction { get; set; }
        public string Collaborations { get; set; }
        public string DevelopmentDesc { get; set; }
        public string proofBusiness { get; set; }
        public string proofMarket { get; set; }
        public string proofSales { get; set; }
        public string proofConceptPayment { get; set; }
        public string finBudget { get; set; }
        public string finVariety { get; set; }
        public string finGrowth { get; set; }
        public string finFacts { get; set; }
        public string riskInvest { get; set; }
        public string riskGoal { get; set; }
        public string Owners { get; set; }
        public string Summary { get; set; }
        public string ProofScale { get; set; }
        public string LookFor2 { get; set; }
    }
}
